#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 24 22:09:02 2019

@author: TristenROBrien
"""
import random
import collections
import numpy as np


def birthday():
    yes = 0 #This will be used to track if there is a birthday match in our test
    no = 0 #This will be used if there is no birthday match in our test
    tries = 0 #This is used to track how many tests we run

    while tries <30: #This number can be changed if you want to run more tests
        x = [] #This stores our results
        for i in range(30): #Thirty people in a room
            birthday = (random.randint(1,366)) #Randomly chooses 30 birthdays 
            x.append(birthday)
            y = list(set(x)) #Used set because a set doesn't allow duplicates

        if len(y) < len(x): #y and x are the same list but y doesn't show duplicates, thus the list will be shorter if there is a match
            yes = yes + 1

        else:
            no = no + 1

        tries = tries + 1
        percent = str(yes/(yes+no)*100)
        percent = percent[:5] #Getting the percentage

    print ('Out of 30 people, there\'s a ' + percent + '% chance of two people having the same birthday.')

birthday()
